### ISSUE TITLE
Spark class loader returns a jar file from getResources

### ISSUE THREAD

**Issue by thormanrd** [rulebook-rules/rulebook#101]
Using the RuleBook in an Apache Spark environment forced me to write another version of the RuleBookRunner to include the processing of a JAR file.  The following snippet was added to the findRuleClassesInPackage in case you want to add it to your base RuleBookRunner...

				else if (Files.exists(ex, new LinkOption[0]) && ex.getFileName().toString().endsWith(".jar")) {
					logger.info("We're going to load classes from a jar");
					ZipInputStream zip = new ZipInputStream(new FileInputStream(ex.getFileName().toString()));
					for (ZipEntry entry = zip.getNextEntry(); entry != null; entry = zip.getNextEntry()) {
						if (!entry.isDirectory() && entry.getName().endsWith(".class")) {
							// This ZipEntry represents a class. Now, what class does it represent?
							String className = entry.getName().replace('/', '.').replace(".class",""); // excluding ".class"
							try {
								Class e = Class.forName(className);
								logger.info("Check {} for annotations", className);
								if(AnnotationUtils.getAnnotation(com.deliveredtechnologies.rulebook.annotation.Rule.class, e) != null) {
									classes.add(e);
									logger.info("added {} to rule book collection", e.getName());
								}
							} catch (ClassNotFoundException var6) {
								logger.error("Unable to resolve class for \'" + packageName + "." + className + "\'", var6);
							}
						}
					}
				}

**Comment by Clayton7510** [comment]
I think there is a fix for this that should work via v0.10 SNAPSHOT. It is still to be confirmed with Spark, however.

**Comment by Clayton7510** [comment]
This should be working now as of the v0.10 release.
