### ISSUE TITLE
Unchecked exception thrown from POJO when() method is handled silently

### ISSUE THREAD

**Issue by jakekugel** [rulebook-rules/rulebook#105]
Hi,
thanks for making this rules engine available.  I'm just starting to play around with Rulebook POJO rules, and due to a bug in my code I was throwing an NPE from the when() method.  It looks like Rulebook silently handles the exception though, treating an exception as a return value of false.

This might be more of a question than an issue, but should an unchecked exception in this case be logged to help debug rule problems?

This is with Rulebook 0.9, and it looks like the code that handles the exception is in RuleAdapter.java, line 133:

```
            try {
              return (Boolean) method.invoke(_rulePojo);
            } catch (InvocationTargetException | IllegalAccessException ex) {
              return false;
            }
```

Thanks,
Jake

**Comment by Clayton7510** [comment]
Jake,

Thanks for raising this!

The scenario you highlighted above is when a POJO rule cannot be invoked. This could happen if say, the @When annotated method was marked private. If that happened then RuleBook could either throw an exception, stop the rule chain or continue processing and treat the failed rule as, well, a failed rule. The 3rd option was chosen. And how RuleBook deals with failed/errored rules is consistent whether you're using the Java DSL, POJO Rules or defining your own RuleBook class with GoldenRules. 

But I agree that it shouldn't be silent. There should at least be something logged like there is when this kind of thing happens with the @Then annotated method.

-Clayton

**Comment by jakekugel** [comment]
Ok thanks for the reply, sounds good.  I'm not sure how you guys like to work, should I submit a pull request to log a message when it happens with the @then method?  

Jake

**Comment by Clayton7510** [comment]
Yep, that works.

**Comment by jakekugel** [comment]
Oops I didn't notice it earlier, but it looks like an exception from then() is already logged, this is line 302-306 of com/deliveredtechnologies/rulebook/runner/RuleAdapter.java in develop branch:

```
        } catch (IllegalAccessException | InvocationTargetException ex) {
          LOGGER.error("Unable to access "
              + _rulePojo.getClass().getName()
              + " when converting then to Consumer", ex);
        }
```
Thanks,
Jake
