### ISSUE TITLE
Few typos in readme found

### ISSUE THREAD

**Issue by tomekbielaszewski** [rulebook-rules/rulebook#115]
Hi,

I've found a few typos in the Readme.md file. I prepared a really small PR to fix this.
If you consider such contribution to be to small to add me to contributors - that's fine. I've done this only for fun.

Cheers!

**Comment by tomekbielaszewski** [comment]
https://github.com/rulebook-rules/rulebook/pull/116

**Comment by Clayton7510** [comment]
Merged and thanks!
