### ISSUE TITLE
Resume engine

### ISSUE THREAD

**Issue by ekoon** [rulebook-rules/rulebook#122]
Say the engine or even application has stopped.  Given the latest Auditor status map from getRuleStatusMap(), is there a way to resume where the application has left off?

**Comment by Clayton7510** [comment]
Not really. I think two things would be needed to re-run a RuleBook from an intermediate state: the Facts at that state and the the next rule to be executed (along with the state of the previous rules' execution for auditing). RuleBooks are run entirely in memory. So, there wouldn't really be a way to recover the Facts at a particular state for a RuleBook.

With that being said, you could certainly extend the existing implementation of CoRRuleBook or create your own RuleBook by implementing the RuleBook interface and persist Facts following the execution of each Rule in the RuleBook.

If you knew what the Facts were that were given to a RuleBook on a particular run, you could also re-run the same Facts with a RuleBook to get what would have been the same outcome. Of course, that also presumes that other state(s) were not manipulated during the execution of the Rules, which may not be a correct assumption.

**Comment by Clayton7510** [comment]
Closed due to inactivity.
