### ISSUE TITLE
HomeLoanRateRuleBook example not working

### ISSUE THREAD

**Issue by wheezymustafa** [rulebook-rules/rulebook#61]
Hello,

Was trying to run through your HomeLoan example and it doesn't appear to be returning any result.  I have the ApplicantBean and the Main classes copied verbatim.  However instantiating the HomeLoanRateRuleBook object gives me a compile error because the following is incompatible:

`HomeLoanRateRuleBook homeLoanRateRuleBook = RuleBookBuilder.create(HomeLoanRateRuleBook).withResultType(Double.class)
      .build();`

Results in "Incompatible types".  Required HomeLoanRateRuleBook, found RuleBook<Double>

If I try casting as HomeLoanRateRuleBook or even setting the variable as:

`RuleBook<Double> homeLoanRateRuleBook = RuleBookBuilder.create(HomeLoanRateRuleBook).withResultType(Double.class)
      .build();`

It does not work.  Any time I run through the steps the RuleBook result (_result) is coming back null.  Only when I specify a defaultResult does it return a value back.  Any ideas?

**Comment by Clayton7510** [comment]
There was a little errata in that example. I just corrected it and verified that the example ran. so, thanks for pointing that out. It looks like it was left over from the v0.5 README update.

If you set a Result type then you will need to specify a default result. The reason for this is because the Result is chained across rules and the default result initializes it so that there's something to chain.

I used the following code to run it. 

```java
public class ExampleSolution {
    public static void main(String[] args) {
        HomeLoanRateRuleBook homeLoanRateRuleBook = (HomeLoanRateRuleBook)RuleBookBuilder.create(HomeLoanRateRuleBook.class).withResultType(Double.class)
                .withDefaultResult(4.5)
                .build();
        NameValueReferableMap facts = new FactMap();
        facts.setValue("applicant", new ApplicantBean(650, 20000.0, true));
        homeLoanRateRuleBook.run(facts);

        homeLoanRateRuleBook.getResult().ifPresent(result -> System.out.println("Applicant qualified for the following rate: " + result));
    }
}
```

You can also declare the rulebook like this.

```java
RuleBook<Double> homeLoanRateRuleBook = RuleBookBuilder.create(HomeLoanRateRuleBook.class).withResultType(Double.class)
                .withDefaultResult(4.5)
                .build();
```

Or like this

```java
HomeLoanRateRuleBook homeLoanRateRuleBook = (HomeLoanRateRuleBook)RuleBookBuilder.create(HomeLoanRateRuleBook.class).withResultType(Double.class)
                .withDefaultResult(4.5)
                .build();
```

**Comment by wheezymustafa** [comment]
Thank you for the update.  I think ensuring the developer sets a defaultResult is an important call out.
