### ISSUE TITLE
Using method not working as expected

### ISSUE THREAD

**Issue by abhineet27** [rulebook-rules/rulebook#62]
In the below example where using is used(highlighted in bold):

RuleBook<String> ruleBook = RuleBookBuilder.create().withResultType(String.class)
				.withDefaultResult("Unknown!")
				.addRule(rule->rule.withFactType(String.class)
				.when(f->f.containsKey("hello") && f.containsKey("world"))
				.**using("hello").then(System.out::print)
				.using("world").then(System.out::println))**
				.build();

The outcome is actually object reference like:
com.deliveredtechnologies.rulebook.TypeConvertibleFactMap@5f4da5c3com.deliveredtechnologies.rulebook.TypeConvertibleFactMap@443b7951

Instead of "Hello World"

**Comment by Clayton7510** [comment]
Thanks for raising this! You are correct. The change to TypeConvertibleFactMap did not include a toString() method that printed the String like FactMap. I'll do a patch sometime this weekend.

**Comment by Clayton7510** [comment]
Fixed in 0.6.1-SNAPSHOT

**Comment by Clayton7510** [comment]
v0.6.1 with fix released to Maven Central

**Comment by abhineet27** [comment]
Yeah, verified it in v6.0.1. Thanks for such a prompt action!
