### ISSUE TITLE
Run several rules each returning a result

### ISSUE THREAD

**Issue by byvlstr** [rulebook-rules/rulebook#64]
Hi,

I have several rules, each having to be triggered (when is true) and so each one should return the name of the winner (some String value). I have been wondering if you have an advice to give me to achieve that. I thought about creating a RuleBook instance per rule, but this is quite tedious and messy. Also, I am using Spring and the Rule logic is quite long, so either I'd have to create a package per Rule (quite messy!) or I'd have to use addRule() on each Rule instance and instanciate them manually.

Thanks!

Valentin

**Comment by Clayton7510** [comment]
Hmm... I'll check it out tonight. If you could post stone example code that you are experiencing problems with, then I can better target your specific issues.

**Comment by Clayton7510** [comment]
Some not stone. Darn smartphone autocorrect. :/

**Comment by byvlstr** [comment]
To give you a bit of context: I have a some competition with an overall winner. But I am using RuleBook to reward other players for some special performances. And there is several rewards, which should all be run through.

I have succeeded I think. I created a "CompositeRule", a real RuleBook rule with all annotations. Inside the then() method, I call the logic of the other rules (which are not RuleBook rules anymore) and the @Result return value is a list of results. By doing that, I can have several results on one RuleBook run.

**Comment by Clayton7510** [comment]
I don't know if I fully understand exactly what conditions you are using to select a winner. But if you are just looking to have a Result with multiple values then there are a few ways you can do that. The most obvious way would be to have a Result that's a collection type, like Map or List, etc. So, something like this:

```java
@Result
Map<String, String> myResultMap;
```

Another thing you could do, is inject the FactMap into a POJO Rule and add facts. This is really nice way to do it if the facts added change impact the evaluation of other rules down the chain. It would be something like this.

```java
@Given
NameValueReferableMap myFactMap;
```

You can then just do the logic in the @Then annotated method. Of course, you could use other classes to do that. But if you have other conditions, it's probably easier to specify other POJO Rules.

You should also note, that you can configure RuleBook's anyway you like, even in Spring. If you have a concise RuleBook, you could just build in the config in Spring and return it as a singleton. I agree that seems a little less elegant than using the provided RuleBookFactoryBean. But it's an option.

**Comment by byvlstr** [comment]
Thanks!
