### ISSUE TITLE
stop() in POJO-Rules with Spring

### ISSUE THREAD

**Issue by imk** [rulebook-rules/rulebook#74]
When using POJO-Rules with Spring, is there any way to configure a Rule as last Rule, like in the DSL-examples: `addRule(RuleBuilder.create().....stop().build());`? Im looking for a way to create a rulebook with different rules that can be executed exclusively (like "only execute the first matching rule"), so i could have a default rule with low order to be executed if there has been no more specific matching rule before.

Don't know if i just haven't found the correct way or there's no way to do this at the moment. And if there's no way to do this at the moment, would it make sense to add this feature or is this a strange use case?

**Comment by Clayton7510** [comment]
I apologize for the delayed response. It's been busy around here.

The equivalent for stop() in a POJO rules would be to have the @Then method in your POJO rule class return a type of RuleState. If the value of the @Then method returned is then RuleState.BREAK that would be equivalent to the stop() method.

**Comment by imk** [comment]
Definitively no reason to apologize, thanks for your response! That's what i've been looking for. Thank you for your effort!
