### ISSUE TITLE
RuleBookRunner.run() => ClassNotFoundException

### ISSUE THREAD

**Issue by hamri** [rulebook-rules/rulebook#95]
Hello,
I'm using RuleBook with play framework and Guice DI. I got ClassNotFoundException after running the rules. Below the code used to create RuleBookRunner:
`bind(RuleBookRunner.class).toInstance(new RuleBookRunner("services.validation.rules"));`

Thanks,

**Comment by Clayton7510** [comment]
I haven't tried it with Guice. Tomorrow and Wednesday are sprint demo + planning @ work. So, it may take me a couple of days to get to it. But I'll definitely check it out this week.

**Comment by hamri** [comment]
Thanks a lot for your help

**Comment by Clayton7510** [comment]
Sorry for the delay. Work was a little nuts this past week. Anyway, I tried out your code above and I didn't seem to have an issue. Perhaps I am missing something with your configuration.

I updated the develop branch with a guice example called megabank-guice here so you can see what I did to configure it with guice: https://github.com/rulebook-rules/rulebook/tree/develop/rulebook-examples

**Comment by Clayton7510** [comment]
Closed due to no response, silence meaning "all good." :)
