### ISSUE TITLE
Refactor Gradle Build Scripts

### ISSUE THREAD

**Issue by Clayton7510** [rulebook-rules/rulebook#99]
Currently, the root project defines most of the functionality for the subprojects. However, as more diverse functionality is needed and other projects are added, there is a need to have the gradle buid scripts pushed down to the subprojects with less common functionality defined in the parent (although common tasks should still be available in the parent). There is also a need to upgrade the version of gradle being used.

**Comment by bradegler** [comment]
I added a small PR for the changes you requested. Let me know if that meets your need for this issue or if you were looking for something more specific.

**Comment by Clayton7510** [comment]
Thanks! I checked out your PR. That definitely helps.
